type Article {
  id: ID
  title: String
  longArticle: String
  tags: [String]
  featureImage: String
  category: String
  slug: String
  secondaryImage: String
  shortArticle: String
  featureVideo: String
  published: Boolean
  createdAt: String
  updatedAt: String
}

input ArticleInput {
  id: ID
  title: String
  slug: String
  longArticle: String
  category: String
  tags: [String]
  featureImage: String
  secondaryImage: String
  shortArticle: String
  featureVideo: String
  published: Boolean
}

input ArticleRecordInput {
  title: String
}

type ArticleIdInput {
  id: ID
}
type ArticleOutput {
  count: Int
  data: [Article]
}
