# import Org from 'org.gql'
# import User from 'user.gql'
# import Role from 'role.gql'
# import Article from 'article.gql'

type Query {
  org(query: OrgInput): OrgOutput
  user(query: UserInput): UserOutput
  role(query: RoleInput): RoleOutput
  article(query: ArticleInput): ArticleOutput
}

type Mutation {
  addOrg(input: OrgInput): Org
  addArticle(input: ArticleInput): Article
  updateArticle(input: ArticleInput): Article
  getArticleByTitle(input: ArticleRecordInput): ArticleOutput
}
